Add connectToPeer and connectFromPeer
Kinda working they do seem to connect:

 $ make run
 bin/main
 Press any key to stop:
 actor1.entryPoint:+
 actor2.entryPoint:+
 actor1.entryPoint:-
 actor2.entryPoint:-
 actor1MasterReceivePort: got ActorCmd.sendPort
 actor2MasterReceivePort: got ActorCmd.sendPortactor1._process: data data=Yo Dude

 actor2._process: data data=Yo Bro
 actor2._process: connectToPeer data=SendPort
 actor1._process: connectFromPeer data=SendPort
 actor2._process: connected msg={ActorCmd: ActorCmd.connected, ActorCmd.data: SendPort}


But I did have this one failure when actor2 was local and actor1 was
in isolate.

 $ make run
 dart2native lib/main.dart -o bin/main
 Generated: /home/wink/prgs/dart/isolate-example2/bin/main
 bin/main
 Press any key to stop:
 actor2.entryPoint:+
 actor1.entryPoint:+
 actor2.entryPoint:-
 actor1.entryPoint:-
 actor2MasterReceivePort: got ActorCmd.sendPort
 actor1MasterReceivePort: got ActorCmd.sendPort
 actor2._process: data data=Yo Bro
 actor1._process: data data=Yo Dudeactor2._process: connectToPeer data=null

 Unhandled exception:
 NoSuchMethodError: The method 'send' was called on null.
 Receiver: null
 Tried calling: send()
 #0      MyActor._process (package:isolate_exmaple/main.dart:115)
 #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
 #2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338)
 #3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265)
 #4      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766)
 #5      _StreamController._add (dart:async/stream_controller.dart:642)
 #6      _StreamController.add (dart:async/stream_controller.dart:588)
 #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174)
 make: *** [makefile:5: run] Error 255